---

- hosts:
    - "meta_role_proxy:&meta_environment_name_{{ environment_name }}"
  become: true
  become_user: root
  roles:
    - role: proxy

    - role: geerlingguy.haproxy
#      haproxy_backend_servers:
#        - name: app1
#          address: 192.168.0.1:80
#        - name: app2
#          address: 192.168.0.2:80

