# from galaxy

# ansible-galaxy -p ./vendor/ install -r requirements.yml --force --ignore-errors

# https://galaxy.ansible.com/geerlingguy/ntp/
- src: geerlingguy.ntp

# https://galaxy.ansible.com/yatesr/timezone/
- src: yatesr.timezone

# https://galaxy.ansible.com/alban.andrieu/jboss/
- src: alban.andrieu.jboss

# https://galaxy.ansible.com/geerlingguy/nodejs/
- src: geerlingguy.nodejs
  version: 2.1.1

# https://galaxy.ansible.com/geerlingguy/git/
- src: geerlingguy.git

# https://galaxy.ansible.com/jdauphant/nginx/
- src: jdauphant.nginx

# https://galaxy.ansible.com/geerlingguy/php/
- src: geerlingguy.php
  version: 2.0.2

# https://galaxy.ansible.com/geerlingguy/redis/
- src: geerlingguy.redis
  version: 1.2.0

# https://galaxy.ansible.com/savagegus/consul/
- src: savagegus.consul
  version: 1.3

# https://galaxy.ansible.com/geerlingguy/haproxy/
- src: geerlingguy.haproxy
  version: 1.0.1


# https://galaxy.ansible.com/franklinkim/nginx/
#- src: franklinkim.nginx

