---

- hosts:
    - "meta_role_web:&meta_environment_name_{{ environment_name }}"
  become: true
  become_user: root
  roles:
    - role: web

    - role: geerlingguy.php
      when: ansible_system == 'Linux'
      php_packages:
        - php5-cli
        - php5-fpm
        - php5-curl
        - php5-gd
        - php5-mysqlnd
        - php5-apcu
        - php5-redis
        - php5-memcached
        - php5-mcrypt
      php_enable_webserver: false
      php_enable_php_fpm: true
      php_opcache_enabled_in_ini: true
      php_apc_enabled_in_ini: true
      php_memory_limit: "128M"
      php_max_execution_time: "90"
      php_upload_max_filesize: "256M"
      php_fpm_listen: "127.0.0.1:9000"

    - role: jdauphant.nginx
      when: ansible_system == 'Linux'
      include_nginx_php: |
        try_files $uri $uri/ /index.php?$args;
        location ~ \.(hh|php)$ {
          try_files     $uri =404;
          fastcgi_pass  127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include       fastcgi_params;
        }
      nginx_sites:
        default:
          - |
            listen 80;
            server_name _;
            root "/app/public";
            index index.php index.html;
            {{ include_nginx_php }}